### ISSUE TITLE
Comments to the README file

### ISSUE THREAD

**Issue by buehlert** [nstudach/sugar#3]
Reading through the README.md, I noticed the following points:
- In case one of the dependencies needs a special version, indicate it here.
- To simplify the usage even more, you could provide config files (without sensitive data, e.g. tokens) and execution commands for all the different measurements you were doing during the thesis.
- Should your final version still have multiple branches, document the differences. E.g. does "debian" contain important instructions only for the debian system?
- Clarify the "inputfile" parameter with an example.
- The SSH section was not completely clear. To which folder "keys" do you refer? It would be nice if your script could support keys in the default location `~/.ssh` as well as keys with non-standard names.
- I know you will add that to your thesis, but it could also be useful to mention the parameters of your successful measurements in the README. E.g. DO image, number of workers, memory size, ...
- If you add stand-alone scripts, you should also document them in the README. For example, how you use `input_modifier.py`

**Comment by nstudach** [comment]
I will add dependencies as requested in #2 
My current working branch is merge_files and I will push it to master today.
The debian branch was already merged with master, it is just not deleted yet.
I am sorry that you put work into looking at an old code in #4, #5, #6  and  #7.
I will still look through the issues and apply changes if they still matter.

Opened specific issues for features
