### ISSUE TITLE
Comments create_droplet.py

### ISSUE THREAD

**Issue by buehlert** [nstudach/sugar#4]
Will this function be used in the final version? Otherwise remove it:
https://github.com/nstudach/sugar/blob/1a41486df6d67d7a0783b675874d111dd920b5f0/create_droplet.py#L9-L17

More expressive name could help:
https://github.com/nstudach/sugar/blob/1a41486df6d67d7a0783b675874d111dd920b5f0/create_droplet.py#L19

Check that the files exist or catch errors:
https://github.com/nstudach/sugar/blob/1a41486df6d67d7a0783b675874d111dd920b5f0/create_droplet.py#L38-L42

Never called?
https://github.com/nstudach/sugar/blob/1a41486df6d67d7a0783b675874d111dd920b5f0/create_droplet.py#L65-L69

Check for errors. What if the `id` is wrong?
https://github.com/nstudach/sugar/blob/1a41486df6d67d7a0783b675874d111dd920b5f0/create_droplet.py#L95

Rather arbitrary, why do you retry exactly once?
https://github.com/nstudach/sugar/blob/1a41486df6d67d7a0783b675874d111dd920b5f0/create_droplet.py#L97-L105

Rename this function as the time package already has a function called sleep:
https://github.com/nstudach/sugar/blob/1a41486df6d67d7a0783b675874d111dd920b5f0/create_droplet.py#L107-L109

Make sure that the argument exists before accessing it. Would advise you to use `argparse`. Then, you could also directly add help strings.
https://github.com/nstudach/sugar/blob/1a41486df6d67d7a0783b675874d111dd920b5f0/create_droplet.py#L113

Would be nice if the user could add as a second parameter the name of the config file. So that you can use different config files for different measurements without renaming them all the time.
Check that config file exists before reading. Print proper error message otherwise.
https://github.com/nstudach/sugar/blob/1a41486df6d67d7a0783b675874d111dd920b5f0/create_droplet.py#L115

What if the user made an error in the config file? Either check before accessing or catch exceptions. Print error messages telling the user exactly which entry was wrong.
https://github.com/nstudach/sugar/blob/1a41486df6d67d7a0783b675874d111dd920b5f0/create_droplet.py#L116-L119

If possible, check first if the region is valid:
https://github.com/nstudach/sugar/blob/1a41486df6d67d7a0783b675874d111dd920b5f0/create_droplet.py#L126

**Comment by nstudach** [comment]
About testing the config file:
Checking each field of the droplet configuration is a bit tedious, but could be done, however if any entry is wrong the droplet will not be created. If however a list, namely the regions entry only has one invalid entry only one droplet creation would fail. Therefore checking the regions is for sure better than not doing it.
