### ISSUE TITLE
Comments run_pathspider.py

### ISSUE THREAD

**Issue by buehlert** [nstudach/sugar#7]
You could also use `from string import ascii_letters, digits`
https://github.com/nstudach/sugar/blob/1a41486df6d67d7a0783b675874d111dd920b5f0/run_pathspider.py#L9

What if the available plugins change?
https://github.com/nstudach/sugar/blob/1a41486df6d67d7a0783b675874d111dd920b5f0/run_pathspider.py#L23-L29

You could also use `defaultdict` from `collections`
https://github.com/nstudach/sugar/blob/1a41486df6d67d7a0783b675874d111dd920b5f0/run_pathspider.py#L37-L39

Here I would also use argparse. Could be interesting to run this script on its own (just to start pathspider). Then it would be easier if you have well defined input parameters and help strings.
https://github.com/nstudach/sugar/blob/1a41486df6d67d7a0783b675874d111dd920b5f0/run_pathspider.py#L50

Check for errors in the config file.
https://github.com/nstudach/sugar/blob/1a41486df6d67d7a0783b675874d111dd920b5f0/run_pathspider.py#L52-L54

Could be useful to have the option to delay the destroying. Just in case you want to manually check something on the VM after the measurement.
https://github.com/nstudach/sugar/blob/1a41486df6d67d7a0783b675874d111dd920b5f0/run_pathspider.py#L120

**Comment by nstudach** [comment]
1.) did not know about string digit and asci letters ->will change
2.) analyzer needs work anyways for IPv6/v4: Could put plugins in config.. maybe
3.) Since collections is in std lib of python -> will change
rest) Implemented in merge files branch
