### ISSUE TITLE
Feature: Hellfire integration

### ISSUE THREAD

**Issue by nstudach** [nstudach/sugar#8]
Integrate hellfire for automatic host list download and splitting via input_modifier.py

**Comment by nstudach** [comment]
Tests have shown that uploading it from a server or locally to each measurement-server is unfeasible for large input files. It would be necessary to integrate an automatic upload to a cloud storage such as dropbox.

**Comment by buehlert** [comment]
In case you keep the two branches (not a problem at all), make sure that the readme files clearly describe the differences.

**Comment by nstudach** [comment]
The hellfire branch was merged into master this morning.
The speed of the copy function was increased by compressing the data first (~10x smaller) and using scp to copy instead of the ParallelSSH copy function (way faster).
